DataDog/build-plugins

.github/workflows/publish.yaml
We can't install a package from the GitHub registry anonymously.
Which is very counter productive.
Publish it on NPM instead.
=> Publish on NPM

.eslintrc.js, .github/workflows/ci.yaml, jest.config.js, src/__tests__/customHook.ignore.ts, src/__tests__/testHelpers.ignore.ts, src/__tests__/webpack.test.ts, src/hooks/__tests__/outputFiles.test.ts, src/hooks/datadog/__tests__/aggregator.test.ts, src/hooks/datadog/__tests__/index.test.ts, src/hooks/datadog/aggregator.ts, src/hooks/datadog/index.ts
Using the build plugin in Yarn's pipeline revealed that the build-plugin doesn't support Node 10.x because of the use of `Array.prototype.flat()`.
- Use an helper function instead of the native function.
- Run tests on older Node versions.
=> Support Node 10

.eslintrc.js, src/__tests__/modules.test.ts, src/modules.ts, src/types.ts
We're missing chunk names in the modules report.
Add `chunkNames` information for each module in the report.
Sometime, a module can be in multiple chunks, so it needs to be an array.
=> Add chunkNames to modules output

README.md, src/hooks/__tests__/outputFiles.test.ts, src/hooks/outputFiles.ts, src/types.ts
It can take some time to write files depending on their size.
And we don't need all of them.
Add the possibility to have an object in the `output` option.
```javascript
{
output: {
destination: 'path/to/destination/',
timings: true
}
}
```
=> Allow object in output option

src/__tests__/esbuild/plugins.test.ts, src/esbuild/index.ts, src/esbuild/plugins.ts
- Our plugin is passing down modified plugins to others which is not great citizenship.
- Computation of the context used in the plugin is weirdly passed down and complexify some calls.
- Pass down an unmodified array of plugins in the event callbacks of other plugins.
- Simplify context creation and computation.
=> Esbuild plugin fixes

src/__tests__/esbuild/modules.test.ts, src/__tests__/helpers/testHelpers.ts, src/esbuild/modules.ts
Esbuild was missing `chunkNames` on its modules.
Add `chunkNames` to each module.
=> [esbuild] add chunknames to esbuild results

package.json, yarn.lock
Let's say you only use `webpack` and you want to use `@datadog/build-plugin`, most package managers will still send a warning because of unmet peer deps on `esbuild`.
And same for the other way.
Use `peerDependenciesMeta` supported by all package managers ([npm](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta), [yarn](https://yarnpkg.com/configuration/manifest#peerDependenciesMeta), and [pnpm](https://pnpm.io/package_json#peerdependenciesmeta)) to mark `webpack` & `esbuild` as optional
=> [peerDependencies] mark as optional

packages/core/src/plugins/global-context/index.ts, packages/core/src/types.ts, packages/plugins/rum/src/types.ts, packages/tests/package.json, packages/tests/src/core/plugins/global-context/index.test.ts, packages/tests/src/helpers/configBundlers.ts, packages/tests/src/helpers/mocks.ts, packages/tests/src/helpers/runBundlers.ts, packages/tests/src/plugins/telemetry/common/metrics/esbuild.test.ts, packages/tests/src/plugins/telemetry/common/metrics/webpack.test.ts, packages/tests/src/plugins/telemetry/testHelpers.ts, packages/tools/package.json
Stacked on https://github.com/DataDog/build-plugins/pull/85
We need a way to communicate the list of files produced at the end of the build.
We're using the global context plugin to gather the list from webpack and esbuild (since they are the only two bundles we support right now).
And add it to the global context.
=> [core] More global contexts

README.md, package.json, packages/plugins/rum/README.md, packages/plugins/rum/package.json, packages/plugins/rum/src/sourcemaps/files.ts, packages/plugins/rum/src/sourcemaps/index.ts, packages/plugins/rum/src/sourcemaps/sender.ts, packages/plugins/rum/src/types.ts, packages/plugins/rum/src/validate.ts, packages/tests/package.json, packages/tests/src/core/plugins/git/index.test.ts, packages/tests/src/core/plugins/global-context/index.test.ts, packages/tests/src/factory/index.test.ts, packages/tests/src/helpers/runBundlers.ts, packages/tests/src/plugins/rum/index.test.ts, packages/tests/src/plugins/rum/sourcemaps/files.test.ts, packages/tests/src/plugins/rum/sourcemaps/sender.test.ts, packages/tests/src/plugins/rum/testHelpers.ts, packages/tests/src/plugins/rum/validate.test.ts, packages/tests/src/plugins/telemetry/common/metrics/esbuild.test.ts, yarn.lock
It leads to some issues to glob into `basePath`, for instance, when your build has multiple entries, in webpack, each entry has its own process, and when globing for sourcemaps, each build will get sourcemaps from the previous build.
This isn't robust enough.
By using the result of the builds, we can only target the files that were generated by the build.
And, we don't need `basePath`'s configuration anymore.
=> [rum] Use context for sourcemaps instead of `basePath`.

README.md, packages/core/src/plugins/git/trackedFilesMatcher.ts, packages/plugins/rum/README.md, packages/plugins/rum/src/sourcemaps/payload.ts, packages/plugins/rum/src/sourcemaps/sender.ts, packages/plugins/rum/src/types.ts, packages/plugins/rum/src/validate.ts, packages/tests/src/plugins/rum/sourcemaps/sender.test.ts, packages/tests/src/plugins/rum/testHelpers.ts, packages/tests/src/plugins/rum/validate.test.ts
We sometimes have hiccups in the sourcemaps upload, but the error gets semi-swallowed and isn't caught.
There was a bug using `p-queue`, `queue.add` is actually async and wasn't awaited, which made the throw not catchable.
Also, we don't always want to fail the full build because we failed to upload one sourcemap.
So we added a `bailOnError` option that is `false` by default.
This refines how we handle errors and add more testing around it as well.
> [!WARNING]
> Since it's changing the default behaviour this will need a minor bump.
=> [rum] Change how we handle errors in sourcemaps upload

packages/core/src/plugins/build-report/esbuild.ts, packages/core/src/plugins/build-report/helpers.ts, packages/core/src/plugins/build-report/webpack.ts, packages/core/src/plugins/index.ts, packages/core/src/plugins/injection/constants.ts, packages/core/src/plugins/injection/helpers.ts, packages/core/src/plugins/injection/index.ts, packages/core/src/types.ts, packages/tests/package.json, packages/tests/src/core/plugins/injection/helpers.test.ts, packages/tests/src/core/plugins/injection/index.test.ts, packages/tests/src/fixtures/file-to-inject.js, packages/tests/src/helpers/mocks.ts, yarn.lock
Having a way to reliably prepend some code to the output bundle would be great.
It needs to:
- support all the currently supported bundlers (webpack4-5, esbuild, rollup and vite).
- be usable from anywhere within the ecosystem.
- support local files, distant files and raw code.
- not conflict with the existing plugins (build report in particular).
Create a pretty simple injection plugin.
It's composed of 4 different elements:
- A `context.inject()` function you'd call to add a new item to inject.
- A preparation plugin, that resolves all the injections.
- A file injection plugin, that injects, within the bundle, a stub file where all the injections live (rollup is different, more on this later)
- A resolution plugin, that resolve the stub file.
> [!NOTE]
> Rollup and Vite are different …
=> [Internal] Injection plugin

packages/tools/src/rollupConfig.mjs
This made our bundle require webpack-sources ALL THE TIME.
Adding `webpack-sources` as an external in rollup's config, makes it require the lib from the top.
Remove the dependency from there, `webpack-sources` is an exception, because it's only loaded dynamically from unplugin's custom webpack/rspack loaders.
=> [fix] Remove webpack-sources from externals

README.md, packages/core/src/types.ts, packages/factory/README.md, packages/factory/src/helpers.ts, packages/factory/src/index.ts, packages/plugins/build-report/src/index.ts, packages/plugins/bundler-report/src/index.ts, packages/plugins/git/src/index.ts, packages/plugins/injection/src/index.ts, packages/plugins/rum/src/index.ts, packages/plugins/telemetry/src/index.ts, packages/tests/src/_jest/helpers/mocks.ts, packages/tests/src/factory/helpers.test.ts, packages/tools/src/commands/integrity/files.ts, packages/tools/src/commands/integrity/readme.ts, packages/tools/src/helpers.ts
Logger requires the plugin itself to instantiate its logger, so it may do it with any name it wants.
We'd need to keep control over how we display logs from other plugins in the ecosystem.
- Pass down an already instantiated logger to all the plugins.
- Allow plugins to create "sub-logger" if they need more granularity on what to log from sub systems.
- Enforce all plugins to export their `PLUGIN_NAME` (using `yarn cli integrity`).
- Add tests.
=> [Logger] Simplify how we instantiate the logger in plugins

packages/plugins/telemetry/src/common/aggregator.ts, packages/plugins/telemetry/src/common/metrics/common.ts, packages/plugins/telemetry/src/common/output/files.ts, packages/plugins/telemetry/src/common/sender.ts, packages/plugins/telemetry/src/index.ts, packages/tests/src/plugins/telemetry/common/aggregator.test.ts, packages/tests/src/plugins/telemetry/common/output/files.test.ts, packages/tests/src/plugins/telemetry/index.test.ts
This is slow and even crashes on very large lists.
Optimise the process using more `Set`s.
=> [perf] Use Set instead of arrays for metrics aggregation

package.json, packages/tools/src/commands/prepare-link/index.ts
This is annoying to test integration in external projects using `yarn link`.
Create a `yarn dev` workflow:
1. Prepare the published packages to be linked by changing their `exports` value so it exports built files.
2. Launch `yarn watch:all` to rebuild anything that changes
3. Once done, it revert the package.json changes.
=> [dx] Add dev mode

packages/core/src/helpers.ts, packages/plugins/build-report/src/helpers.ts, packages/plugins/build-report/src/index.ts, packages/plugins/build-report/src/xpack.ts, packages/plugins/telemetry/src/common/sender.ts
https://github.com/DataDog/build-plugins/pull/112 introduced a bug in the sender of our telemetry plugin.
- Transform set into array right before sending metrics to DD.
- Add some comments here and there.
- Narrow down the entry filepath detection on xspack's build-report.
=> [fix] Small fixes

LICENSE, NOTICE, packages/published/esbuild-plugin/src/index.ts, packages/published/rollup-plugin/src/index.ts, packages/published/rspack-plugin/src/index.ts, packages/published/vite-plugin/src/index.ts, packages/published/webpack-plugin/src/index.ts
https://github.com/DataDog/build-plugins/issues/126
Seems like rollup's `dts` plugin doesn't navigate through an `export [...] from [...]`.
Fix #126
=> [types] Fix exported type of Options

.github/workflows/bump.yaml, .github/workflows/publish.yaml, package.json
Having a way to manually bump the versions without checking out `master` would be great.
- Add a new `bump` action.
1. run `yarn version:all <patch|minor|major>` based on the input of the workflow dispatch.
2. commit the diff in `v<new_version>`.
3. tag the commit with `v<new_version>`. 
[Successful run.](https://github.com/DataDog/build-plugins/actions/runs/13418889087/job/37486473979)
=> [ci] Release process update

.github/CODEOWNERS, packages/core/src/types.ts, packages/factory/README.md, packages/factory/package.json, packages/factory/src/helpers.ts, packages/factory/src/index.ts, packages/plugins/analytics/README.md, packages/plugins/analytics/package.json, packages/plugins/analytics/src/constants.ts, packages/plugins/analytics/src/index.ts, packages/plugins/analytics/tsconfig.json, packages/tests/src/_jest/helpers/mocks.ts, packages/tests/src/unit/plugins/analytics/index.test.ts, yarn.lock
We need a way to better understand how users are using the build plugins and with which bundler.
TLDR; Submit a log to Datadog with very basic informations, once the build has started.
[Logs are visible here.](https://app.datadoghq.com/logs?query=service%3Abuild-plugins&agg_m=count&agg_m_source=base&agg_t=count&cols=core_host%2Ccore_service%2Csource%2Cbundler.name&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1739617377098&to_ts=1739876577098&live=true)
=> [logging] Add meta reporting

packages/core/src/helpers/server.test.ts, packages/core/src/helpers/server.ts, packages/tools/src/commands/dev-server/index.ts
- #151 
In preparation of [[feat] Add synthetics plugin](https://github.com/DataDog/build-plugins/pull/153) we extract the dev server implementation into a core helper.
It's mostly a code move with some small additions to allow for a more basic utilisation.
- streamlining server responses.
- adding a `middleware` feature so `yarn cli dev-server` can implement its templating feature.
- adding a `routes` feature so `@dd/synthetics-plugin` can implement its routes for inter communication with `datadog-ci`.
=> [internal] Move dev server helper

packages/core/src/types.ts, packages/factory/README.md, packages/factory/src/helpers/logger.test.ts, packages/factory/src/helpers/logger.ts, packages/tests/src/_jest/helpers/mocks.ts
To improve observability and provide richer insights into build performance, this PR enhances the span logger with tagging capabilities. 
This allows us to attach contextual information to each span and/or timer, making debugging and performance analysis more granular (also better prepared for DD submission). 
Additionally, streamlined mock implementations are added to improve testing of the logging functionality.
- Modified the span logger to return timer object for more flexible usage
- Added tagging capabilities to the time logger to annotate spans with contextual metadata
- Integrated timer into the build report sooner in the process
- Streamlined mock implementations to simplify and strengthen testing
> This project adds automated performance profiling to build plugins by …
=> [log] Add tags and mocks to span logger

packages/core/src/helpers/plugins.test.ts, packages/core/src/helpers/plugins.ts, packages/factory/src/helpers/logger.ts, packages/tools/src/commands/create-plugin/ask.ts, packages/tools/src/commands/create-plugin/index.test.ts
Plugin names are currently processed inconsistently across the codebase, leading to potential inconsistencies in logs, spans, and metrics.
This PR creates a centralized helper function for plugin name normalization to ensure consistent naming conventions throughout the build system.
- Created a dedicated `cleanPluginName` helper function to standardize how plugin names are formatted and sanitized
- Updated all plugin name handling code to use this central helper
- Ensures consistent plugin names in logs, spans, and metrics for better observability
> This project adds automated performance profiling to build plugins by standardizing plugin naming, enhancing logging capabilities, and refactoring the plugin initialization system to provide detailed execution insights without manual …
=> [internal] Update, fix and extract `cleanPluginName`

packages/tools/src/commands/prepare-link/index.ts
Running `yarn dev` or `yarn cli prepare-link` would mutate the `package.json`'s `exports` field and replace its content with the default value.
Which is problematic for `@datadog/rollup-plugin`, because we also have a "basic" build for it, that we use to instrument ourselves.
Save the previous value of `exports` into `previousExports` and re-use it during the reset.
=> [fix] Do not mutate existing exports fields

MIGRATIONS.md, README.md, packages/core/src/helpers/request.test.ts, packages/core/src/types.ts, packages/factory/src/helpers/context.test.ts, packages/factory/src/validate.ts, packages/plugins/error-tracking/README.md, packages/plugins/error-tracking/src/sourcemaps/sender.test.ts, packages/plugins/error-tracking/src/sourcemaps/sender.ts, packages/plugins/error-tracking/src/types.ts, packages/plugins/error-tracking/src/validate.test.ts, packages/plugins/error-tracking/src/validate.ts, packages/plugins/git/src/index.test.ts, packages/plugins/rum/src/sdk.test.ts, packages/plugins/rum/src/sdk.ts, packages/plugins/telemetry/README.md, packages/plugins/telemetry/src/common/helpers.test.ts, packages/plugins/telemetry/src/common/helpers.ts, packages/plugins/telemetry/src/common/sender.ts, packages/plugins/telemetry/src/index.test.ts, packages/plugins/telemetry/src/index.ts, packages/plugins/telemetry/src/types.ts, packages/tests/src/_jest/helpers/env.ts, packages/tests/src/_jest/helpers/mocks.ts, packages/tools/src/rollupConfig.test.ts
This PR introduces a unified site configuration that centralizes the Datadog site definition under `auth.site`. This replaces the individual endpoint configurations that were previously
scattered across different plugins.
- **Added `auth.site` configuration**: A single source of truth for the Datadog site (defaults to `'datadoghq.com'`)
- **Removed redundant configurations**, now computed from `auth.site`:
- `telemetry.endPoint`
- `errorTracking.sourcemaps.intakeUrl`
- **Environment variable support**: `DATADOG_SITE` takes priority over configuration
- **Backward compatibility**: `DATADOG_SOURCEMAP_INTAKE_URL` still works as an override
```diff
{
auth: {
apiKey: 'xxx',
+       site: 'datadoghq.eu'
},
telemetry: {
-       endPoint: 'https://app.datadoghq.eu'
},
errorTracking: {
sourcemaps: …
```
=> [auth] Unify `site` configuration used for API requests

.github/workflows/ci.yaml, packages/plugins/injection/src/esbuild.ts, packages/plugins/injection/src/index.test.ts, packages/plugins/injection/src/xpack.ts
The injection plugin was creating non deterministic build chunk hashes because the name of the virtual files used in the injection plugin used a random string to enforce uniqueness and reduce potential conflicts between parallel builds.
Remove unique IDs from stub injection file names in the injection plugin.
This simplifies the file naming by using a consistent, predictable format for temporary injection files and helps make the build more deterministic.
- **Removed unique ID generation**: Eliminated the use of `getUniqueId()` from injection file paths in both esbuild and xpack implementations. Replaced it with the name of the bundler in order to avoid "some" collisions while keeping it deterministic.
- **Updated unit tests**: Re-enforce the tests by expecting no errors from the builds …
=> [fix] Remove uniqueId from the stub injection files

.github/CODEOWNERS, README.md, packages/core/src/helpers/plugins.ts, packages/core/src/types.ts, packages/factory/package.json, packages/factory/src/index.ts, packages/plugins/build-report/src/index.test.ts, packages/plugins/injection/src/index.test.ts, packages/plugins/metrics/src/index.test.ts, packages/plugins/output/README.md, packages/plugins/output/package.json, packages/plugins/output/src/constants.ts, packages/plugins/output/src/index.test.ts, packages/plugins/output/src/index.ts, packages/plugins/output/src/types.ts, packages/plugins/output/src/validate.test.ts, packages/plugins/output/src/validate.ts, packages/plugins/output/tsconfig.json, packages/published/esbuild-plugin/src/index.ts, packages/published/rollup-plugin/src/index.ts, packages/published/rspack-plugin/src/index.ts, packages/published/vite-plugin/src/index.ts, packages/published/webpack-plugin/src/index.ts, packages/tools/src/commands/create-plugin/templates.ts, yarn.lock
This PR adds the Output Plugin, providing the ability to export build reports, metrics, and bundler data to JSON files for analysis and/or monitoring.
- **New `output` plugin** (`packages/plugins/output/`) that exports various build artifacts to JSON files including build reports, metrics, timings, logs, errors, warnings, dependencies, and bundler data
- **Migrated debug functionality** from the separate debugFilesPlugin to be incorporated directly into the Output Plugin for better consolidation
- **Smaller fixes**
- Fix `create-plugin` with updated templates.
- Fixed some documentations.
=> [feat] Output plugin

.github/chainguard/self.bump.sts.yaml, .github/workflows/bump.yaml
Since we now have a `v2` branch, we need to be able to bump versions from it.
Update the policy for the bump action.
=> [security] Make bump action allowed on the `v2` branch
